# Generated by Django 3.1.3 on 2021-11-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_image',
            field=models.ImageField(default='p.png', upload_to='products', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_name',
            field=models.CharField(max_length=200, verbose_name='Product Name'),
        ),
    ]
